# Generated by Django 6.0.1 on 2026-01-15 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='LOGIN, LOGOUT, CREATE, UPDATE, DELETE, etc', max_length=50, verbose_name='Accion')),
                ('resource', models.CharField(help_text='Recurso afectado', max_length=200, verbose_name='Recurso')),
                ('result', models.CharField(choices=[('SUCCESS', 'Exito'), ('FAILURE', 'Fallo')], max_length=20, verbose_name='Resultado')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Detalles adicionales')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log Auditoria',
                'verbose_name_plural': 'Logs Auditoria',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx'), models.Index(fields=['user', '-timestamp'], name='audit_logs_user_id_e11c73_idx'), models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx')],
            },
        ),
    ]
