# Generated by Django 6.0.1 on 2026-01-21 10:42

import apps.utils.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)', verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True, verbose_name='Eliminado en')),
                ('fecha', models.DateField(db_index=True, help_text='Fecha de las llamadas')),
                ('telefono', models.CharField(db_index=True, help_text='Número telefónico que realizó llamadas', max_length=20, validators=[apps.utils.validators.validate_phone_number])),
                ('servicio_800', models.CharField(db_index=True, help_text='Número servicio 800 destino', max_length=20, validators=[apps.utils.validators.validate_service_800])),
                ('total_llamadas', models.IntegerField(default=0, help_text='Total de llamadas realizadas', validators=[django.core.validators.MinValueValidator(0)])),
                ('llamadas_contestadas', models.IntegerField(default=0, help_text='Llamadas contestadas por agente', validators=[django.core.validators.MinValueValidator(0)])),
                ('llamadas_abandonadas', models.IntegerField(default=0, help_text='Llamadas abandonadas (colgadas antes de contestar)', validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion_total_segundos', models.IntegerField(default=0, help_text='Duración total en segundos', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp creación registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp última actualización')),
            ],
            options={
                'verbose_name': 'Registro de Llamada',
                'verbose_name_plural': 'Registros de Llamadas',
                'db_table': 'core_call_records',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['fecha', 'servicio_800'], name='core_call_r_fecha_960fab_idx'), models.Index(fields=['fecha', 'telefono'], name='core_call_r_fecha_b2b83b_idx'), models.Index(fields=['-fecha', '-total_llamadas'], name='core_call_r_fecha_980b6e_idx')],
                'unique_together': {('fecha', 'telefono', 'servicio_800')},
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)', verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True, verbose_name='Eliminado en')),
                ('nombre', models.CharField(help_text='Nombre del centro de atención', max_length=200)),
                ('codigo', models.CharField(db_index=True, help_text='Código único del centro (ej: CT01, CENTER_SCL)', max_length=20, unique=True, validators=[apps.utils.validators.validate_codigo_center])),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del centro')),
                ('direccion', models.CharField(blank=True, help_text='Dirección física del centro', max_length=500)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='¿Centro actualmente operativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
            ],
            options={
                'verbose_name': 'Centro',
                'verbose_name_plural': 'Centros',
                'db_table': 'core_centers',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activo', 'codigo'], name='core_center_activo_613c4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ETLExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('end_date', models.DateField(verbose_name='Fecha fin')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'Ejecutando'), ('SUCCESS', 'Exitoso'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('records_extracted', models.IntegerField(default=0, help_text='Cantidad de registros extraidos de IVR', verbose_name='Registros extraidos')),
                ('records_loaded', models.IntegerField(default=0, help_text='Cantidad de registros cargados en Analytics', verbose_name='Registros cargados')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
            ],
            options={
                'verbose_name': 'Ejecucion ETL',
                'verbose_name_plural': 'Ejecuciones ETL',
                'db_table': 'etl_executions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='etl_executi_started_30cb87_idx'), models.Index(fields=['status', '-started_at'], name='etl_executi_status_e374a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)', verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True, verbose_name='Eliminado en')),
                ('numero_800', models.CharField(db_index=True, help_text='Número servicio 800 (ej: 800-123-4567)', max_length=20, unique=True, validators=[apps.utils.validators.validate_service_800])),
                ('nombre', models.CharField(help_text='Nombre del servicio', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del servicio')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='¿Servicio actualmente operativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('center', models.ForeignKey(help_text='Centro al que pertenece el servicio', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='pipeline.center')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'core_services',
                'ordering': ['numero_800'],
                'indexes': [models.Index(fields=['activo', 'numero_800'], name='core_servic_activo_d8a537_idx'), models.Index(fields=['center', 'activo'], name='core_servic_center__66aa64_idx')],
            },
        ),
    ]
