# Generated by Django 5.0.14 on 2026-01-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETLExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('end_date', models.DateField(verbose_name='Fecha fin')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'Ejecutando'), ('SUCCESS', 'Exitoso'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('records_extracted', models.IntegerField(default=0, help_text='Cantidad de registros extraidos de IVR', verbose_name='Registros extraidos')),
                ('records_loaded', models.IntegerField(default=0, help_text='Cantidad de registros cargados en Analytics', verbose_name='Registros cargados')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
            ],
            options={
                'verbose_name': 'Ejecucion ETL',
                'verbose_name_plural': 'Ejecuciones ETL',
                'db_table': 'etl_executions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='etl_executi_started_30cb87_idx'), models.Index(fields=['status', '-started_at'], name='etl_executi_status_e374a8_idx')],
            },
        ),
    ]
