# Generated by Django 5.0.14 on 2026-01-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True)),
                ('question', models.CharField(help_text='Pregunta de seguridad', max_length=200, unique=True, verbose_name='Pregunta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pregunta Seguridad',
                'verbose_name_plural': 'Preguntas Seguridad',
                'db_table': 'security_questions',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='UserSecurityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True)),
                ('answer_hash', models.CharField(help_text='Respuesta hasheada', max_length=128, verbose_name='Respuesta (hash)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.securityquestion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta Seguridad',
                'verbose_name_plural': 'Respuestas Seguridad',
                'db_table': 'user_security_answers',
            },
        ),
    ]
