# Generated by Django 6.0.1 on 2026-01-24 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)', verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True, verbose_name='Eliminado en')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('condition', models.JSONField(help_text='Condición en formato JSON', verbose_name='Condición')),
                ('priority', models.CharField(choices=[('info', 'Informativa'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítica')], default='info', max_length=10, verbose_name='Prioridad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='Última evaluación')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Último disparo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Configuración de Alerta',
                'verbose_name_plural': 'Configuraciones de Alertas',
                'db_table': 'alerts_alert_configuration',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='idx_alert_active'), models.Index(fields=['-created_at'], name='idx_alert_created')],
            },
        ),
        migrations.CreateModel(
            name='InternalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)', verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True, verbose_name='Eliminado en')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('body', models.TextField(verbose_name='Contenido')),
                ('priority', models.CharField(choices=[('info', 'Informativa'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítica')], default='info', max_length=10, verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje Interno',
                'verbose_name_plural': 'Mensajes Internos',
                'db_table': 'alerts_internal_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepción')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipients', to='alerts.internalmessage', verbose_name='Mensaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Destinatario de Mensaje',
                'verbose_name_plural': 'Destinatarios de Mensajes',
                'db_table': 'alerts_message_recipient',
            },
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', through='alerts.MessageRecipient', to=settings.AUTH_USER_MODEL, verbose_name='Destinatarios'),
        ),
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)', verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True, verbose_name='Eliminado en')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suscripción')),
                ('alert_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='alerts.alertconfiguration', verbose_name='Configuración de Alerta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción a Alerta',
                'verbose_name_plural': 'Suscripciones a Alertas',
                'db_table': 'alerts_alert_subscription',
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_sub_user_active')],
                'unique_together': {('user', 'alert_configuration')},
            },
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['user', 'read_at'], name='idx_rcpt_user_read'),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['user', 'archived_at'], name='idx_rcpt_user_arch'),
        ),
        migrations.AlterUniqueTogether(
            name='messagerecipient',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='internalmessage',
            index=models.Index(fields=['-created_at'], name='idx_msg_created'),
        ),
        migrations.AddIndex(
            model_name='internalmessage',
            index=models.Index(fields=['sender', '-created_at'], name='idx_msg_sender'),
        ),
        migrations.AddIndex(
            model_name='internalmessage',
            index=models.Index(fields=['priority'], name='idx_msg_priority'),
        ),
    ]
