# Generated by Django 6.0.1 on 2026-01-15 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: ve_reportes, crea_usuarios', max_length=50, unique=True, verbose_name='Codigo funcion')),
                ('module', models.CharField(help_text='Ej: MOD_Reports, MOD_Users', max_length=50, verbose_name='Modulo')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Funcion',
                'verbose_name_plural': 'Funciones',
                'db_table': 'functions',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UserFunctionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(help_text='Por que se asigna esta funcion', verbose_name='Justificacion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revocada en')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functions_assigned_by_me', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='access.function', verbose_name='Funcion')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functions_revoked_by_me', to=settings.AUTH_USER_MODEL, verbose_name='Revocada por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignacion Funcion',
                'verbose_name_plural': 'Asignaciones Funciones',
                'db_table': 'user_function_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'function')},
            },
        ),
    ]
