# Generated by Django 5.0.1 on 2026-01-22 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Function",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indica si el registro está eliminado (delete lógico)",
                        verbose_name="Eliminado",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se eliminó el registro",
                        null=True,
                        verbose_name="Eliminado en",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Ej: ve_reportes, crea_usuarios",
                        max_length=50,
                        unique=True,
                        verbose_name="Codigo funcion",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Ej: MOD_Reports, MOD_Users",
                        max_length=50,
                        verbose_name="Modulo",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripcion"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Funcion",
                "verbose_name_plural": "Funciones",
                "db_table": "functions",
                "ordering": ["module", "code"],
            },
        ),
        migrations.CreateModel(
            name="UserFunctionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indica si el registro está eliminado (delete lógico)",
                        verbose_name="Eliminado",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se eliminó el registro",
                        null=True,
                        verbose_name="Eliminado en",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(
                        help_text="Por que se asigna esta funcion",
                        verbose_name="Justificacion",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revocada en"
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignacion Funcion",
                "verbose_name_plural": "Asignaciones Funciones",
                "db_table": "user_function_assignments",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="UserModuleAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indica si el registro está eliminado (delete lógico)",
                        verbose_name="Eliminado",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se eliminó el registro",
                        null=True,
                        verbose_name="Eliminado en",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Otorgado en"),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Por qué se otorgó este acceso",
                        verbose_name="Razón",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revocado en"
                    ),
                ),
            ],
            options={
                "verbose_name": "Acceso a Módulo",
                "verbose_name_plural": "Accesos a Módulos",
                "db_table": "user_module_accesses",
                "ordering": ["-granted_at"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indica si el registro está eliminado (delete lógico)",
                        verbose_name="Eliminado",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se eliminó el registro",
                        null=True,
                        verbose_name="Eliminado en",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del módulo (ej: MOD_Dashboard)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del módulo",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del módulo",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Orden de visualización",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono (ej: dashboard, report)",
                        max_length=50,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "url_path",
                    models.CharField(
                        blank=True,
                        help_text="Ruta URL del módulo (ej: /dashboard)",
                        max_length=200,
                        verbose_name="URL Path",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Módulo activo en el sistema",
                        verbose_name="Activo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Módulo padre en la jerarquía (None para raíz)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="access.module",
                        verbose_name="Módulo padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo",
                "verbose_name_plural": "Módulos",
                "db_table": "modules",
                "ordering": ["order", "code"],
            },
        ),
    ]
