# Generated by Django 6.0.1 on 2026-01-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userserviceaccess',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='userserviceaccess',
            name='core_user_s_user_id_5bf15e_idx',
        ),
        migrations.RemoveIndex(
            model_name='userserviceaccess',
            name='core_user_s_service_68040f_idx',
        ),
        migrations.RemoveIndex(
            model_name='userserviceaccess',
            name='core_user_s_is_acti_2dc2f4_idx',
        ),
        migrations.DeleteModel(
            name='UserServiceAccess',
        ),
    ]
