# Generated by Django 5.0.1 on 2026-01-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, help_text='Fecha de las llamadas')),
                ('telefono', models.CharField(db_index=True, help_text='Numero telefonico que realizo llamadas', max_length=20)),
                ('servicio_800', models.CharField(db_index=True, help_text='Numero servicio 800 destino', max_length=20)),
                ('total_llamadas', models.IntegerField(default=0, help_text='Total de llamadas realizadas')),
                ('llamadas_contestadas', models.IntegerField(default=0, help_text='Llamadas contestadas por agente')),
                ('llamadas_abandonadas', models.IntegerField(default=0, help_text='Llamadas abandonadas (colgadas antes de contestar)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp creacion registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp ultima actualizacion')),
            ],
            options={
                'verbose_name': 'Registro de Llamada',
                'verbose_name_plural': 'Registros de Llamadas',
                'db_table': 'core_call_records',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['fecha', 'servicio_800'], name='core_call_r_fecha_960fab_idx'), models.Index(fields=['fecha', 'telefono'], name='core_call_r_fecha_b2b83b_idx')],
                'unique_together': {('fecha', 'telefono', 'servicio_800')},
            },
        ),
    ]
