# Generated by Django 5.0.14 on 2026-01-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True)),
                ('nombre', models.CharField(help_text='Nombre del centro', max_length=200)),
                ('codigo', models.CharField(db_index=True, help_text='Codigo unico del centro', max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Centro activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centro',
                'verbose_name_plural': 'Centros',
                'db_table': 'core_centers',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UserServiceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Otorgado en')),
                ('reason', models.TextField(blank=True, help_text='Por qué se otorgó este acceso', verbose_name='Razón')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revocado en')),
            ],
            options={
                'verbose_name': 'Acceso a Servicio',
                'verbose_name_plural': 'Accesos a Servicios',
                'db_table': 'user_service_accesses',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True)),
                ('fecha', models.DateField(db_index=True, help_text='Fecha de las llamadas')),
                ('telefono', models.CharField(db_index=True, help_text='Numero telefonico que realizo llamadas', max_length=20)),
                ('servicio_800', models.CharField(db_index=True, help_text='Numero servicio 800 destino', max_length=20)),
                ('total_llamadas', models.IntegerField(default=0, help_text='Total de llamadas realizadas')),
                ('llamadas_contestadas', models.IntegerField(default=0, help_text='Llamadas contestadas por agente')),
                ('llamadas_abandonadas', models.IntegerField(default=0, help_text='Llamadas abandonadas (colgadas antes de contestar)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp creacion registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp ultima actualizacion')),
            ],
            options={
                'verbose_name': 'Registro de Llamada',
                'verbose_name_plural': 'Registros de Llamadas',
                'db_table': 'core_call_records',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['fecha', 'servicio_800'], name='core_call_r_fecha_960fab_idx'), models.Index(fields=['fecha', 'telefono'], name='core_call_r_fecha_b2b83b_idx')],
                'unique_together': {('fecha', 'telefono', 'servicio_800')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True)),
                ('numero_800', models.CharField(db_index=True, help_text='Numero servicio 800', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del servicio', max_length=200)),
                ('activo', models.BooleanField(default=True, help_text='Servicio activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(help_text='Centro al que pertenece', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.center')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'core_services',
                'ordering': ['numero_800'],
            },
        ),
    ]
