# Generated by Django 5.0.1 on 2026-01-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del centro', max_length=200)),
                ('codigo', models.CharField(db_index=True, help_text='Codigo unico del centro', max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Centro activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centro',
                'verbose_name_plural': 'Centros',
                'db_table': 'core_centers',
                'ordering': ['nombre'],
            },
        ),
    ]
