# Generated by Django 5.0.14 on 2026-01-16 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userserviceaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_accesses_granted', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por'),
        ),
        migrations.AddField(
            model_name='userserviceaccess',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_accesses_revoked', to=settings.AUTH_USER_MODEL, verbose_name='Revocado por'),
        ),
        migrations.AddField(
            model_name='userserviceaccess',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='core.service', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='userserviceaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='userserviceaccess',
            index=models.Index(fields=['user', 'is_active'], name='user_servic_user_id_841005_idx'),
        ),
        migrations.AddIndex(
            model_name='userserviceaccess',
            index=models.Index(fields=['service', 'is_active'], name='user_servic_service_2dbec0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userserviceaccess',
            unique_together={('user', 'service')},
        ),
    ]
