# Generated by Django 5.0.1 on 2026-01-14 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_800', models.CharField(db_index=True, help_text='Numero servicio 800', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del servicio', max_length=200)),
                ('activo', models.BooleanField(default=True, help_text='Servicio activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(help_text='Centro al que pertenece', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.center')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'core_services',
                'ordering': ['numero_800'],
            },
        ),
    ]
